### ISSUE TITLE
Query Example or Document Ready

### ISSUE THREAD

**Issue by abbashajihashemi** [artisansdk/cqrs#2]
Hi
First of all thanks for this package.
I installed this package with all dependencies and I have one issue with how create a query and use it in my controller. Did you can give me a example or get me info about when you complete package documentation?
Thanks

**Comment by alaovich** [comment]
Hi,
Thanks for this package. I've the same problem when i want create a queries :(
Regards,

**Comment by dalabarge** [comment]
Thanks for using the package. Sorry I'm just now seeing these comments. I've just updated the readme to include some semi-comprehensive documentation on using queries. They are very much similar to commands but with an expectation of using the `builder()` method. They are eventable the same as commands. They are not transactional because by nature they are reading data not writing data. They are however cacheable to avoid executing expensive queries such as those against API services too frequently. Like with commands, you can also add macros/mixins to further customize the command and query buses to your liking. If there's specific examples missing from the readme, please open another issue with a use case example so I can document it.

See the readme: https://github.com/artisansdk/cqrs#queries
