### ISSUE TITLE
Support Class Command and CommandHandler

### ISSUE THREAD

**Issue by tanmnt** [artisansdk/cqrs#6]
Thank you for this package.

I find that currently using arguments in a command makes it very difficult to know how many inputs the command.

**Comment by dalabarge** [comment]
Are you finding it hard to know how many inputs a command has defined? Typically the way I handle this is with some docblocks. Let's assume I have a `RegisterUser` command that takes as required arguments an email address, password, and optionally the first name and last name of the user.

1. You can use `@param` or `@property` docblock annotations to define these arguments on the command.
2. Alternatively you could use `@method` annotation to describe the dynamic method assignment.

See example below:

```php
namespace App\Commands;

use App\User;
use ArtisanSdk\CQRS\Command;

/**
 * Register the User
 *
 * @example $user = RegisterUser::make()
 *           ->email('johndoe@example.com')
 *           ->password('secret')
 *           ->run();
 *
 * @example $user = RegisterUser::make()
 *           ->email('johndoe@example.com')
 *           ->password('secret')
 *           ->firstName('John')
 *           ->lastName('Doe')
 *           ->run();
 * 
 * @param string $email required
 * @param string $password required, plaint text
 * @param string? $first_name optional
 * @param string? $last_name optional
 *
 * @method string|self email(string $value)
 * @method string|self password(string $value)
 * @method string?|self firstName(string? $value = null)
 * @method string?|self lastName(string? $value = null)
 */
class RegisterUser extends Command
{
       public function __invoke() : User
       {
              $user = new User();

              // Mass assignment way of doing it without validation
              $user->fill($this->arguments()); // one way of doing it

              // Manual assignment way of doing it with validation
              $user->email = strtolower($this->argument('email', ['email']));
              $user->password = Hash::make($this->argument('password', ['string', 'between:6-24']));
              $user->first_name = $this->option('first_name');
              $user->last_name = $this->option('last_name');
              $user->save();

              return $user;
       }
}
```

Ultimately the command is only programmed to handle certain arguments and options: this affords the developer the program anything they want as argument/option and pass to the command but the command will ignore what it does not know about.

I suppose one way of making this binding of arguments/options to the command more contractual in code, we could develop the builder class to accept a validated argument set. That would be something like the following:

```php
/**
  * @property string $email
  * @property string $password
  * @property string? $first_name
  * @property string? $last_name
  *
  * @method string|self email(string $value)
  * @method string|self password(string $value)
  * @method string?|self firstName(string? $value = null)
  * @method string?|self lastName(string? $value = null)
  */
class RegisterUserArguments extends Arguments
{
      public function rules() : array 
      {
              return [
                   'email' => ['required', 'string', 'email'],
                   'password' => ['required', 'string', 'between:6,24'],
                   'first_name' => ['nullable', 'string', 'max:32'],
                   'last_name' => ['nullable', 'string', 'max:32'],
              ];
      }
}

// Procedural
$arguments = new RegisterUserArguments();
$arguments->email = 'johndoe@example.com';
$arguments->first_name = 'John';
$arguments->last_name = 'Doe';
$arguments->foo = 'bar'; // throws error as foo is not defined
$arguments->validate(); // throws error because required argument password is not set

// Fluent Builder
$arguments = (new RegisterUserArguments())
       ->email('johndoe@example.com')
       ->firstName('John')
       ->lastName('Doe')
       ->foo('bar') // throws error as foo is not defined
       ->validate(); // throws error because required argument password is not set

// Pass validated arguments to the command
$user = RegisterUser::make($arguments))->run();
```

You could also skip the `validate()` method as the `make()` or `run()` methods on the `RegisterUser` could run `validate()` automatically at runtime prior to executing the `__invoke()` method itself. Then you'd know for sure you have validated arguments and options if set. The `Arguments` class would be a base class you could compose and pass to a command but you'd want to extend it instead. So then you would bind `RegisterUser` to `RegisterUserArguments` class such that the only way to pass arguments to `RegisterUser` is via `RegisterUserArguments` class.  It's a lot more boilerplate and there's other ways of consolidating the `rules()` onto the `RegisterUser` command directly if consolidation of argument validation is all that's needed.

Is that something you're looking for? Would that be more helpful? Is it a matter of looking at code and knowing what a valid argument is or is it a matter of having your IDE autocomplete available methods?  You might find docblocks is all that is really needed because the typed `Arguments` classes require additional bindings to clarify arguments and enforce argument safety at the expense of more boilerplate.

**Comment by dalabarge** [comment]
We just release `1.0.0-rc3` which corrects intellisense when using `Command::make()` or `Query::make()`. Perhaps that's what you were originally referring to but it helps the intellisense parsers navigate with the correct type hints.
